### ISSUE TITLE
Consider a different name

### ISSUE THREAD

**Issue by robinbowes** [pote/gpm#59]
I'm looking at packaging gpm (for CentOS) so I can use it to build some go packages.

However, there is already a package named ```gpm```:

```
 yum info gpm
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.openitc.uk
 * epel: mirror.vorboss.net
 * extras: centos.openitc.uk
 * fasttrack: centos.openitc.uk
 * updates: centos.openitc.uk
Available Packages
Name        : gpm
Arch        : x86_64
Version     : 1.20.7
Release     : 5.el7
Size        : 183 k
Repo        : base/7/x86_64
Summary     : A mouse server for the Linux console
URL         : http://www.nico.schottelius.org/software/gpm/
License     : GPLv2 and GPLv2+ with exceptions and GPLv3+ and Verbatim and Copyright only
Description : Gpm provides mouse support to text-based Linux applications like the
            : Emacs editor and the Midnight Commander file management system.  Gpm
            : also provides console cut-and-paste operations using the mouse and
            : includes a program to allow pop-up menus to appear at the click of a
            : mouse button.
```

Might you consider using a different name, eg. ```gopm```?

**Comment by pote** [comment]
That's a toughie, we've gone through a name change already earlier in the life of the project, making another switch would be pretty involved and I honestly don't see it happening.

Maybe what we could do is add something to the makefile to allow for a different name on the executable? I'd be open to merging that in if it means supporting more users!

**Comment by robinbowes** [comment]
That wouldn't really help, as anything that currently uses ```gpm``` would break if the name of the executable changed between platforms.

**Comment by pote** [comment]
#65 Fixes this particular need, closing the issue! :dancer:
