### ISSUE TITLE
Handle private repos out-of-the-box

### ISSUE THREAD

**Issue by parkr** [pote/gpm#69]
I've been looking for a good way to ship go packages with private dependencies short of Godeps' solution of putting them in the git source tree for the depending project. Would gpm consider a feature like this? Perhaps there's some modifier in the dependencies file that could indicate that it should be fetched over SSH?

Thanks for making gpm! We love it over at VSCO.

**Comment by pote** [comment]
Thank you so much for the kind words! I'm happy you find it useful :) 

There's [already a way of using dependencies stored in private repos without vendoring them](https://github.com/pote/gpm#private-repos), does that one work for you?

**Comment by parkr** [comment]
Yes! Had no clue. Thank you!

**Comment by pote** [comment]
No problem! :heart: :dancer:
