### ISSUE TITLE
Fatal errors installing non-root packages

### ISSUE THREAD

**Issue by jdb-vsn** [pote/gpm#75]
I'm trying to install the protobuf support with gpm, but the actual go packages aren't in the root of their repo.  `github.com/golang/protobuf` is the repo root, but the actual packages are `github.com/golang/protobuf/proto` and `github.com/golang/protobuf/protoc-gen-go`

If I put the actual packages in my Godeps file, I get this error:
```
>> Getting package github.com/golang/protobuf/proto
>> Getting package github.com/golang/protobuf/protoc-gen-go
# cd .; git clone https://github.com/golang/protobuf /projects/go-ext/src/github.com/golang/protobuf
fatal: destination path '/projects/go-ext/src/github.com/golang/protobuf' already exists and is not an empty directory.
package github.com/golang/protobuf/protoc-gen-go: exit status 128
>> Setting github.com/golang/protobuf/proto to version efd7476481382c195beb33acd8ec2f1527167fb4
>> Setting github.com/golang/protobuf/protoc-gen-go to version efd7476481382c195beb33acd8ec2f1527167fb4
fatal: Unable to create '/projects/go-ext/src/github.com/golang/protobuf/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
>> Building package github.com/golang/protobuf/proto
>> Building package github.com/golang/protobuf/protoc-gen-go
>> All Done
-e 
Success
```

If I put the root repo in the file, I get this:
```
>> Getting package github.com/golang/protobuf
package github.com/golang/protobuf
	imports github.com/golang/protobuf
	imports github.com/golang/protobuf: no buildable Go source files in /projects/go-ext/src/github.com/golang/protobuf
>> Setting github.com/golang/protobuf to version efd7476481382c195beb33acd8ec2f1527167fb4
>> Building package github.com/golang/protobuf
can't load package: package github.com/golang/protobuf: no buildable Go source files in /projects/go-ext/src/github.com/golang/protobuf
```

**EDIT**: Despite the fatal error messages in the output, `protoc-gen-go` does get installed, but it is certainly ugly and unexpected to see fatals in the output.

**Comment by elcuervo** [comment]
Can confirm unexpected behaviour on those packages. Already planning a fix ^_^

**Comment by pote** [comment]
Hey @jdb-vsn ! You can get this package installed by adding the following line to your Godeps file:

```
github.com/golang/protobuf/...    efd7476481382c195beb33acd8ec2f1527167fb4
```

Notice the `/...` at the end, that tells the go tool to install all packages inside that repository. The reason why we don't allow subpackages to be added to the Godeps file is that that would imply that you can have two subpackages that belong to the same repository locked in different versions (which isn't true), so the policy is to only have top-level import paths in the Godeps file.

It can be a bit counterintuitive at first, but I think it helps keep in mind that the go tool and gpm work by cloning a repository and setting a desired version on it and there is value in that. Hope this helps!
